"""remove_unique_tool_name

Revision ID: 1b631c8765f2
Revises: 534f7072898d
Create Date: 2026-07-21 12:37:15.157316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b631c8765f2'
down_revision: Union[str, None] = '534f7072898d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tools_name', table_name='tools')
    op.create_index('ix_tools_name', 'tools', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tools_name', table_name='tools')
    op.create_index('ix_tools_name', 'tools', ['name'], unique=True)
    # ### end Alembic commands ###
