"""remove_user_fields

Revision ID: 20b16d1d140e
Revises: 572586e4dfb8
Create Date: 2026-06-29 15:34:03.477666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20b16d1d140e'
down_revision: Union[str, None] = '572586e4dfb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'provider')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
