"""add_google_oauth_fields_to_users

Revision ID: c34d443b864f
Revises: f4389c9b1223
Create Date: 2026-07-08 14:35:26.013687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c34d443b864f'
down_revision: Union[str, None] = 'f4389c9b1223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    # Add is_active as nullable first, set default, then make not null
    op.add_column('users', sa.Column('is_active', sa.Integer(), nullable=True))
    op.execute("UPDATE users SET is_active = 1 WHERE is_active IS NULL")
    op.alter_column('users', 'is_active', nullable=False, server_default='1')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
