"""create_tool_steps_many_to_many

Revision ID: c7c11616d15a
Revises: e0d6ae51ba09
Create Date: 2026-07-09 09:38:01.750338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7c11616d15a'
down_revision: Union[str, None] = 'e0d6ae51ba09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_steps',
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tool_id', 'step_id')
    )
    # Migrate data from tools.step_id to tool_steps table
    op.execute(
        "INSERT INTO tool_steps (tool_id, step_id) "
        "SELECT id, step_id FROM tools WHERE step_id IS NOT NULL"
    )
    op.drop_constraint('tools_step_id_fkey', 'tools', type_='foreignkey')
    op.drop_column('tools', 'step_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('step_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tools_step_id_fkey', 'tools', 'steps', ['step_id'], ['id'], ondelete='SET NULL')
    # Migrate data back (set step_id to the first associated step in tool_steps)
    op.execute(
        "UPDATE tools SET step_id = ("
        "SELECT step_id FROM tool_steps WHERE tool_steps.tool_id = tools.id LIMIT 1)"
    )
    op.drop_table('tool_steps')
    # ### end Alembic commands ###
