"""align schema with database md

Revision ID: f4389c9b1223
Revises: 375f6361ee69
Create Date: 2026-07-08 06:29:53.454860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4389c9b1223'
down_revision: Union[str, None] = '375f6361ee69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Clear rows with non-integer IDs before altering column types
    op.execute("DELETE FROM steps WHERE id !~ '^[0-9]+$'")
    op.execute("DELETE FROM tools WHERE id !~ '^[0-9]+$'")

    op.alter_column('steps', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               postgresql_using='id::integer')
    op.alter_column('tools', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               postgresql_using='id::integer')


    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tool_categories',
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tool_id', 'category_id')
    )
    op.create_table('tool_guide_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_prompts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_recommended', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_roles',
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tool_id', 'role')
    )
    op.create_table('tool_prompt_categories',
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_id'], ['tool_prompts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prompt_id', 'category_id')
    )
    op.create_table('tool_prompt_roles',
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['tool_prompts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prompt_id', 'role')
    )
    op.add_column('tools', sa.Column('visibility', sa.String(length=10), server_default='public', nullable=False))
    op.add_column('tools', sa.Column('login_ids', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=True))
    op.add_column('tools', sa.Column('guide_content', sa.Text(), nullable=True))
    op.add_column('tools', sa.Column('admin_memo', sa.Text(), nullable=True))
    op.add_column('tools', sa.Column('step_id', sa.Integer(), nullable=True))
    op.alter_column('tools', 'details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_foreign_key(None, 'tools', 'steps', ['step_id'], ['id'], ondelete='SET NULL')
    op.drop_column('tools', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('category', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tools', type_='foreignkey')
    op.alter_column('tools', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('tools', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('tools', 'step_id')
    op.drop_column('tools', 'admin_memo')
    op.drop_column('tools', 'guide_content')
    op.drop_column('tools', 'login_ids')
    op.drop_column('tools', 'visibility')
    op.alter_column('steps', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_table('tool_prompt_roles')
    op.drop_table('tool_prompt_categories')
    op.drop_table('tool_roles')
    op.drop_table('tool_prompts')
    op.drop_table('tool_guide_files')
    op.drop_table('tool_categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
